[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.24.3"
tract-onnx = "0.16.5"

[[bin]]
name = "detect"
path = "src/detect.rs"

[features]
default = ["image"]
image = []
