[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path = "../core" }
wasm-bindgen = "0.2.82"

# M1チップのMac環境対応
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
